#!/usr/bin/env node

/* todo 静态生成支持 */

require("dotenv").config();
const { withPromise } = require("./prod-entry");

process.env.NODE_ENV = "production";

withPromise().then(() => {
  console.log("start static page generate...");
});
