#!/usr/bin/env node

require("dotenv").config();
const { getDynamicRouter } = require("./dynamic");

process.env.NODE_ENV = "development";

global.isMiddleWareDevelop = process.env.MIDDLEWARE && JSON.parse(process.env.MIDDLEWARE);

// first get dynamic router
getDynamicRouter().then(() => {
  require("./dev-entry").start();
});
